# Generated by Django 4.1.2 on 2022-12-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_api', '0002_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='content/'),
        ),
    ]
