# Generated by Django 4.1.2 on 2022-12-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_api', '0003_alter_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='product_image',
        ),
    ]
